require 'pry'
require 'nokogiri'
require 'open-uri'
require 'colorize'

require_relative '../lib/classes/scraper.rb'
require_relative '../lib/classes/cli.rb'
require_relative '../lib/classes/menu.rb'
require_relative '../lib/classes/characters.rb'
require_relative '../lib/classes/devilfruit.rb'
require_relative '../lib/classes/effects.rb'
require_relative '../lib/classes/version.rb'